AllCops:
  Include:
    - 'lib/**/*'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    # It is too heavy with math and formulae
    - 'lib/geo/coord/globes.rb'
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'tmp/*'
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "[]"

Metrics/ClassLength:
  Max: 260

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 14

Gemspec/OrderedDependencies:
  Enabled: false
